### ISSUE TITLE
Gradients become NaN after first step()

### ISSUE THREAD

**Issue by MarcusLimJunYi** [rollovd/LookSAM#1]
Thank you very much for the implementation of LookSAM! But there seems to be a tiny bug that causes the gradients to become NaNs. 

https://github.com/rollovd/LookSAM/blob/90eb622139ff89fbfad21a9394956ff4acb7d184/looksam.py#L59

There should an additional epsilon of 1e-8. 
return g / (g.norm(p=2) + **1e-8**)
I've made the change in my own code and the NaNs don't appear anymore. Do update this in your free time and once again thanks for the implementation!

**Comment by rollovd** [comment]
Yeah, thank you! 

In addition, I put in order the whole method. Thus, you are able to leverage a "fixed" version. :)
